#! /usr/bin/env python

import re

text = open("gni_pub.h").read()
matches = re.compile("gni_return_t.*?(GNI_.*?;)", re.DOTALL).findall(text)
str_arr = []
for m in matches:
  fxn_arr = []
  line_arr = m.strip().splitlines()
  fxn_arr = ['extern "C" gni_return_t %s' % line_arr[0]]
  for line in line_arr[1:-1]:
    line = line.replace("IN","").replace("OUT","").strip()
    fxn_arr.append("  " + line)
  fxn_arr[-1] += ") {";
  fxn_arr.append('  spkt_abort_printf("unimplemented: %s)");' % line_arr[0])
  fxn_arr.append("}")
  str_arr.append("\n".join(fxn_arr))
print "\n\n".join(str_arr)

