# Define the following to 1 to enable build
BENCH_GTC_MPI = 1
BENCH_CHARGEI_PTHREADS = 0
BENCH_PUSHI_PTHREADS = 0
BENCH_SERIAL = 0

CC = sstcc
MPICC = sstcc
CFLAGS = -g -O0 -DUSE_MPI=1 
COPTFLAGS = -O3
CDEPFLAGS = -MD 
CLDFLAGS = -lm 

EXEEXT = _sst

AR = ar
ARCRFLAGS = cr
RANLIB = ranlib

