# Define the following to 1 to enable build
BENCH_GTC_MPI = 1
BENCH_CHARGEI_PTHREADS = 0
BENCH_PUSHI_PTHREADS = 0
BENCH_SERIAL = 0

CC = tau_cc.sh
MPICC = tau_cc.sh
CFLAGS = -DUSE_MPI=1
CFLAGSOMP = -qsmp=omp:noauto
COPTFLAGS = -O3 -g
CDEPFLAGS = 
#CLDFLAGS = -L/home/morozov/lib -lmpihpm_smp -L/bgsys/drivers/ppcfloor/bgpm/lib -lbgpm        
#LIB:=/bgsys/drivers/ppcfloor/spi/lib/libSPI_upci_cnk.a
#CLDFLAGS = 
MPIDIR = 
CFLAGS  +=

EXEEXT = _vesta_opt_tau

AR = ar
ARCRFLAGS = cr
RANLIB = ranlib
